// This file was automatically generated by the Dapper.SimpleCRUD T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `CePing`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=.;Initial Catalog=CePing;User ID=sa;Password=******;`
//     Include Views:          `True`

using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Collections.Generic;

namespace YiWei.TestingEvaluation.Entity.TT
{
    /// <summary>
    /// A class which represents the Member table.
    /// </summary>
	[Table("Member")]
	public partial class Member
	{
		[Key]
		public virtual string OpenId { get; set; }
		public virtual string NikeName { get; set; }
		public virtual string HeadUrl { get; set; }
		public virtual int? Sex { get; set; }
		public virtual int? Subscribe { get; set; }
		public virtual DateTime? SubscribeTime { get; set; }
		public virtual string Name { get; set; }
		public virtual DateTime? Birthdate { get; set; }
		public virtual string Mobile { get; set; }
		public virtual int? ProvinceId { get; set; }
		public virtual int? CityId { get; set; }
		public virtual int? DistrictId { get; set; }
		public virtual int? MemberType { get; set; }
		public virtual DateTime? CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the MBTI_ReportText table.
    /// </summary>
	[Table("MBTI_ReportText")]
	public partial class MBTIReportText
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual string TypeCodeName { get; set; }
		public virtual string TypeCodeNameEn { get; set; }
		public virtual string TypicalCharacters { get; set; }
		public virtual string TypicalCharactersProfile { get; set; }
		public virtual string TypicalCharactersImg { get; set; }
		public virtual string Positive { get; set; }
		public virtual string Negative { get; set; }
	}

    /// <summary>
    /// A class which represents the MBTI_Question table.
    /// </summary>
	[Table("MBTI_Question")]
	public partial class MBTIQuestion
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual string Question { get; set; }
		public virtual string AOption { get; set; }
		public virtual string AAnswer { get; set; }
		public virtual string BOption { get; set; }
		public virtual string BAnswer { get; set; }
		public virtual int? TesingId { get; set; }
	}

    /// <summary>
    /// A class which represents the AreaData table.
    /// </summary>
	[Table("AreaData")]
	public partial class AreaData
	{
		[Key]
		public virtual int Id { get; set; }
		public virtual int? AreaId { get; set; }
		public virtual int? AreaLevel { get; set; }
		public virtual string ShortCNName { get; set; }
		public virtual string FullName { get; set; }
		public virtual string ShortEnName { get; set; }
		public virtual string EnName { get; set; }
		public virtual int? IfProvincialCapital { get; set; }
		public virtual string LevelPath { get; set; }
		public virtual string AreaNamePath { get; set; }
		public virtual int? SortOrder { get; set; }
		public virtual string Code { get; set; }
	}

    /// <summary>
    /// A class which represents the OrderInfo table.
    /// </summary>
	[Table("OrderInfo")]
	public partial class OrderInfo
	{
		[Key]
		public virtual string OrderNo { get; set; }
		public virtual string OpenId { get; set; }
		public virtual string ProductCode { get; set; }
		public virtual string ProductName { get; set; }
		public virtual decimal? OriginalPrice { get; set; }
		public virtual decimal? DiscountPrice { get; set; }
		public virtual int? Number { get; set; }
		public virtual decimal? TotalAmount { get; set; }
		public virtual decimal? PayAmount { get; set; }
		public virtual string PayMethod { get; set; }
		public virtual int? Status { get; set; }
		public virtual string Remarks { get; set; }
		public virtual string InterfaceOrderNumber { get; set; }
		public virtual string InterfaceBuyer { get; set; }
		public virtual DateTime? CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the MBTI_Report table.
    /// </summary>
	[Table("MBTI_Report")]
	public partial class MBTIReport
	{
		[Key]
		public virtual long Id { get; set; }
		public virtual string OpenId { get; set; }
		public virtual int? E { get; set; }
		public virtual int? I { get; set; }
		public virtual int? S { get; set; }
		public virtual int? N { get; set; }
		public virtual int? T { get; set; }
		public virtual int? F { get; set; }
		public virtual int? J { get; set; }
		public virtual int? P { get; set; }
		public virtual string TypeCode { get; set; }
		public virtual int? TestingType { get; set; }
		public virtual string OrderNo { get; set; }
		public virtual int? IsFinished { get; set; }
		public virtual DateTime CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the MemberChildren table.
    /// </summary>
	[Table("MemberChildren")]
	public partial class MemberChildren
	{
		[Key]
		public virtual long Id { get; set; }
		public virtual string BelongToOpenId { get; set; }
		public virtual string ChildrenName { get; set; }
		public virtual int? ChildrenSex { get; set; }
		public virtual DateTime? Birthdate { get; set; }
		public virtual int? GaokaoProvince { get; set; }
		public virtual string Grade { get; set; }
		public virtual int? EnterSchoolYear { get; set; }
		public virtual string SchoolName { get; set; }
		public virtual DateTime? CreateDate { get; set; }
	}

    /// <summary>
    /// A class which represents the LogWxPayNotify table.
    /// </summary>
	[Table("LogWxPayNotify")]
	public partial class LogWxPayNotify
	{
		[Key]
		public virtual long Id { get; set; }
		public virtual string TransactionId { get; set; }
		public virtual string ReturnCode { get; set; }
		public virtual string ResultCode { get; set; }
		public virtual string ReturnMsg { get; set; }
		public virtual string OpenId { get; set; }
		public virtual string OutTradeNo { get; set; }
		public virtual string Attach { get; set; }
		public virtual int? TotalFee { get; set; }
		public virtual DateTime? CtreateTime { get; set; }
	}

    /// <summary>
    /// A class which represents the SysAccessToken table.
    /// </summary>
	[Table("SysAccessToken")]
	public partial class SysAccessToken
	{
		[Key]
		public virtual int TId { get; set; }
		public virtual string access_token { get; set; }
		public virtual int expires_in { get; set; }
		public virtual DateTime LastTime { get; set; }
	}

}
